export type Product = {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  shortDescription?: string | null;
  price: number;
  compareAtPrice?: number | null;
  stock: number;
  sku?: string | null;
  brand?: string | null;
  categoryId?: string | null;
  category?: string;
  categorySlug?: string;
  images: string[];
  thumbnail?: string | null;
  isFeatured: boolean;
  isActive: boolean;
  tags: string[];
  rating?: number | null;
  reviewCount: number;
  warranty?: string | null;
  dimensions?: string | null;
  weight?: number | null;
  source?: string | null;
  sourceId?: string | null;
  sourceUrl?: string | null;
  scrapedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
  isFlashSale?: boolean;
  isBestSeller?: boolean;
};